# Generated by Django 4.2 on 2023-05-01 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogItems',
            fields=[
                ('BacklogItemID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(null=True)),
                ('Projected_Hours', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Actual_Hours', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Start_Date', models.DateField(null=True)),
                ('End_Date', models.DateField(null=True)),
                ('Plan', models.TextField(null=True)),
                ('Note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('EthnicityID', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('GenderID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeCycle',
            fields=[
                ('LifeCycleID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('OrganizationID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProjectID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(null=True)),
                ('Start_Date', models.DateField(null=True)),
                ('End_Date', models.DateField(null=True)),
                ('Note', models.TextField(null=True)),
                ('LifeCycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lifecycle')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholders',
            fields=[
                ('StakeholderID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50, null=True)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.CharField(max_length=50, null=True)),
                ('Note', models.TextField(null=True)),
                ('Ethnicity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ethnicity')),
                ('Gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gender')),
                ('Organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.organizations')),
                ('User', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('TypeID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkEvents',
            fields=[
                ('WorkEventID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Work_Date', models.DateField(null=True)),
                ('Start_Time', models.TimeField(null=True)),
                ('End_Time', models.TimeField(null=True)),
                ('Duration', models.DurationField(null=True)),
                ('Work', models.TextField(null=True)),
                ('Next_Steps', models.TextField(null=True)),
                ('Note', models.TextField(null=True)),
                ('Backlog_Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.backlogitems')),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stakeholders')),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stakeholders'),
        ),
        migrations.AddField(
            model_name='projects',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.types'),
        ),
        migrations.AddField(
            model_name='backlogitems',
            name='Assigned_To',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stakeholders'),
        ),
        migrations.AddField(
            model_name='backlogitems',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.projects'),
        ),
        migrations.AddField(
            model_name='backlogitems',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
        migrations.CreateModel(
            name='Assginments',
            fields=[
                ('AssignmentsID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Assignment_Date', models.DateField(null=True)),
                ('Note', models.TextField(null=True)),
                ('Project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
                ('Role', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.roles')),
                ('Stakeholder', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.stakeholders')),
            ],
        ),
    ]
