# Generated by Django 4.2 on 2023-05-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assginments',
            new_name='Assignments',
        ),
    ]
