# Generated by Django 4.2 on 2023-05-02 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_rename_assginments_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.projects'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='Role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.roles'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='Stakeholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.stakeholders'),
        ),
        migrations.AlterField(
            model_name='backlogitems',
            name='Assigned_To',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.stakeholders'),
        ),
        migrations.AlterField(
            model_name='backlogitems',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.projects'),
        ),
        migrations.AlterField(
            model_name='backlogitems',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.types'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='LifeCycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lifecycle'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.stakeholders'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='Ethnicity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ethnicity'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gender'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='Organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organizations'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workevents',
            name='Backlog_Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.backlogitems'),
        ),
        migrations.AlterField(
            model_name='workevents',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.stakeholders'),
        ),
        migrations.AlterField(
            model_name='workevents',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.projects'),
        ),
    ]
