# Generated by Django 4.2 on 2023-05-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ethnicity_ethnicityid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='AssignmentsID',
            new_name='AssignmentID',
        ),
    ]
